name: flutter_application_3
description: A new Flutter project.

publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  get: ^4.6.6 
  app_links: ^6.1.4
  wakelock_plus: ^1.0.2
  standard_searchbar: ^2.0.0
  hexagon: ^0.2.0
  window_manager: ^0.4.3
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.3.0
  firebase_auth: ^5.5.1
  image_field: ^0.0.10
  platform_file: ^0.1.0
  file_picker: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/mtg-background.png
    - images/sloth.png
    - images/wubrg_logo.png
    - images/kuriboh.png
  fonts:
  - family: Belwe 
    fonts:
      - asset: fonts/Belwe Bold.otf
