name: flutter_application_3
description: A new Flutter project.

publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  standard_searchbar: ^2.0.0
  hexagon: ^0.2.0
  window_manager: ^0.2.7
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.3.0
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/mtg-background.png
    - images/sloth.png
    - images/wubrg_logo.png
    - images/kuriboh.png
  fonts:
  - family: Belwe 
    fonts:
      - asset: fonts/Belwe Bold.otf
